AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  MyFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: .
      Timeout: 50
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
